# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: TypeScript Compile Package

on:
  release:
    types: [published]

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v18
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Install Yarn with NPM
      run: npm install -g yarn
    - name: yarn install
      run: yarn install
    - name: Compile TypeScript
      run: |
        set -e
        rm -rf dist
        NODE_ENV=production npm exec -- tsc
        NODE_ENV=production npm exec -- rollup -c
    - name: Rename build artifact
      run: mv dist/web/index.js esptool.js
    - name: upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: esptool.js